name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Set up Nodejs 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: |
        #git submodule update --init --recursive
        rm -rf themes/icarus
        git clone https://github.com/ppoffice/hexo-theme-icarus.git themes/icarus -b 2.4.0 --depth 1
        npm install bulma-stylus@0.8.0 hexo@^4.2.0 hexo-component-inferno@^0.4.0 hexo-log@^1.0.0 hexo-pagination@^1.0.0 hexo-renderer-inferno@^0.1.3 hexo-renderer-stylus@^1.1.0 hexo-util@^1.8.0 inferno@^7.3.3 inferno-create-element@^7.3.3
        bash .travis/_install.sh
    - name: Build
      env:
        GITHUB_PAT: ${{ secrets.ALL_GH_PAT }}
        STEEM_ACCOUNTS: jackzeng6666
        GIT_USERNAME: steemblogger
        GIT_EMAIL: hello@rdpstudio.top
        DURATION: 7
        DEBUG: true
        BLOG_REPO: steemblogger/steemblogger.github.io
        API_NODE: https://api.steemit.com
        TRAVIS_BRANCH: master
      run: |
        bash .travis/_build.sh
    - name: Deploy
      env:
        GITHUB_PAT: ${{ secrets.ALL_GH_PAT }}
        STEEM_ACCOUNTS: jackzeng6666
        GIT_USERNAME: steemblogger
        GIT_EMAIL: hello@rdpstudio.top
        DURATION: 7
        DEBUG: true
        BLOG_REPO: steemblogger/steemblogger.github.io
        API_NODE: https://api.steemit.com
        TRAVIS_BRANCH: master
      run: |
        bash .travis/_deploy.sh
        
